version: '3.7'

services:
  bind9:
    image: internetsystemsconsortium/bind9:9.16
    restart: always
    container_name: my-dns
    ports:
    - "53:53/tcp"
    - "53:53/udp"
    - "127.0.0.1:953:953/tcp"
    volumes:
      - ./bind:/etc/bind
      - /var/cache/bind
      - /var/lib/bind
      - /var/log
